import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { spawn } from "node:child_process";
import { tmpdir } from "node:os";
import { randomBytes } from "node:crypto";
import type { GlobalSslConfig, LetsEncryptConfig } from "@worktreeos/core/global-config";
import { wosHome } from "@worktreeos/core/paths";

export const CERTS_DIRNAME = "certs";

export type SslListenerKind = "web" | "tunnel";

export interface ResolvedTlsMaterial {
  cert: string;
  key: string;
  certPath: string;
  keyPath: string;
  /** True when both files were generated by the resolver. */
  generated: boolean;
}

export interface LetsEncryptResolveInput {
  letsencrypt: LetsEncryptConfig;
  /** Required hostnames the issued certificate must cover. */
  requiredHostnames: string[];
  kind: SslListenerKind;
  env: NodeJS.ProcessEnv;
}

export interface ResolveSslOptions {
  /** SSL config for the listener. */
  ssl: GlobalSslConfig;
  /** Which listener is being resolved (controls generated file names + SANs). */
  kind: SslListenerKind;
  /** Subject Alternative Name DNS entries used when generating a self-signed certificate. */
  sanDns?: string[];
  /** Subject Alternative Name IP entries used when generating a self-signed certificate. */
  sanIp?: string[];
  /** Required hostnames for Let's Encrypt issuance. */
  requiredHostnames?: string[];
  /** Process env (for `<wos-home>` resolution). Defaults to `process.env`. */
  env?: NodeJS.ProcessEnv;
  /**
   * Override the openssl-based certificate generator (tests). Receives the
   * desired SAN entries and returns PEM-encoded `cert` and `key` contents.
   */
  generateSelfSigned?: (input: SelfSignedInput) => Promise<SelfSignedOutput>;
  /**
   * Resolve Let's Encrypt-managed material via the ACME manager. Required
   * when `ssl.source === "letsencrypt"`.
   */
  resolveLetsEncrypt?: (
    input: LetsEncryptResolveInput,
  ) => Promise<ResolvedTlsMaterial>;
}

export interface SelfSignedInput {
  commonName: string;
  sanDns: string[];
  sanIp: string[];
}

export interface SelfSignedOutput {
  cert: string;
  key: string;
}

export function certsDir(env: NodeJS.ProcessEnv = process.env): string {
  return resolve(wosHome(env), CERTS_DIRNAME);
}

export function generatedCertPaths(
  kind: SslListenerKind,
  env: NodeJS.ProcessEnv = process.env,
): { cert: string; key: string } {
  const dir = certsDir(env);
  return {
    cert: resolve(dir, `${kind}-self-signed.crt`),
    key: resolve(dir, `${kind}-self-signed.key`),
  };
}

/**
 * Resolve TLS material for an SSL-enabled listener. Reads configured
 * certificate/key paths or generates a persistent self-signed pair under
 * `<wos-home>/certs`.
 *
 * Throws an `Error` with an actionable message when the configured paths
 * cannot be read or generation fails. Callers should catch and degrade the
 * listener accordingly.
 */
export async function resolveSslMaterial(
  opts: ResolveSslOptions,
): Promise<ResolvedTlsMaterial> {
  if (!opts.ssl.enabled) {
    throw new Error("resolveSslMaterial called with disabled SSL config");
  }
  const env = opts.env ?? process.env;
  const cfg = opts.ssl;

  if (cfg.source === "files") {
    const cert = await readFileOrThrow(cfg.cert, `${opts.kind}.ssl.cert`);
    const key = await readFileOrThrow(cfg.key, `${opts.kind}.ssl.key`);
    return {
      cert,
      key,
      certPath: cfg.cert,
      keyPath: cfg.key,
      generated: false,
    };
  }

  if (cfg.source === "letsencrypt") {
    if (!opts.resolveLetsEncrypt) {
      throw new Error(
        `${opts.kind}.ssl.source=letsencrypt but no ACME resolver was provided`,
      );
    }
    return await opts.resolveLetsEncrypt({
      letsencrypt: cfg.letsencrypt,
      requiredHostnames: dedupe(opts.requiredHostnames ?? []),
      kind: opts.kind,
      env,
    });
  }

  // self-signed branch.
  const paths = generatedCertPaths(opts.kind, env);
  if (existsSync(paths.cert) && existsSync(paths.key)) {
    const cert = await readFileOrThrow(paths.cert, `${opts.kind}.ssl generated cert`);
    const key = await readFileOrThrow(paths.key, `${opts.kind}.ssl generated key`);
    return {
      cert,
      key,
      certPath: paths.cert,
      keyPath: paths.key,
      generated: true,
    };
  }

  const generator = opts.generateSelfSigned ?? generateWithOpenssl;
  const sanDns = dedupe(opts.sanDns ?? []);
  const sanIp = dedupe(opts.sanIp ?? []);
  const commonName =
    sanDns[0] ?? (opts.kind === "web" ? "localhost" : "tunnel.local");
  let generated: SelfSignedOutput;
  try {
    generated = await generator({ commonName, sanDns, sanIp });
  } catch (e) {
    throw new Error(
      `${opts.kind} SSL self-signed certificate generation failed: ${(e as Error).message}`,
    );
  }

  await mkdir(certsDir(env), { recursive: true, mode: 0o700 });
  await writeFile(paths.cert, generated.cert, { mode: 0o600 });
  await writeFile(paths.key, generated.key, { mode: 0o600 });
  try {
    await chmod(paths.cert, 0o600);
    await chmod(paths.key, 0o600);
  } catch {
    // chmod fallback for filesystems that ignored the open mode.
  }

  return {
    cert: generated.cert,
    key: generated.key,
    certPath: paths.cert,
    keyPath: paths.key,
    generated: true,
  };
}

async function readFileOrThrow(path: string, label: string): Promise<string> {
  try {
    return await readFile(path, "utf8");
  } catch (e) {
    throw new Error(`could not read ${label} at ${path}: ${(e as Error).message}`);
  }
}

function dedupe(values: string[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const v of values) {
    if (!v || v.length === 0) continue;
    if (seen.has(v)) continue;
    seen.add(v);
    out.push(v);
  }
  return out;
}

/**
 * Build the list of hostnames Let's Encrypt must cover for the Web UI listener.
 * Returns the effective public Web UI hostname when present, otherwise an
 * empty list. Loopback and reserved hostnames are filtered out — callers
 * should treat an empty list as a configuration error.
 */
export function buildWebLetsEncryptHostnames(opts: {
  publicHostname?: string;
}): string[] {
  if (!opts.publicHostname || opts.publicHostname.length === 0) return [];
  return dedupe([opts.publicHostname]);
}

/**
 * Build the list of hostnames Let's Encrypt must cover for the tunnel listener.
 * Always includes `tunnel.domain` plus `*.${tunnel.domain}` so a single cert
 * covers both root and app subdomains.
 */
export function buildTunnelLetsEncryptHostnames(opts: {
  tunnelDomain: string;
}): string[] {
  if (!opts.tunnelDomain || opts.tunnelDomain.length === 0) return [];
  return dedupe([opts.tunnelDomain, `*.${opts.tunnelDomain}`]);
}

/** Build a SAN list, deduped, used for generating a self-signed certificate. */
export function buildWebSanInputs(opts: {
  publicHostname?: string;
}): { sanDns: string[]; sanIp: string[] } {
  const sanDns: string[] = ["localhost"];
  if (opts.publicHostname && opts.publicHostname.length > 0) {
    sanDns.push(opts.publicHostname);
  }
  return { sanDns: dedupe(sanDns), sanIp: dedupe(["127.0.0.1", "::1"]) };
}

export function buildTunnelSanInputs(opts: {
  tunnelDomain: string;
}): { sanDns: string[]; sanIp: string[] } {
  const sanDns: string[] = [];
  if (opts.tunnelDomain.length > 0) {
    sanDns.push(opts.tunnelDomain);
    sanDns.push(`*.${opts.tunnelDomain}`);
  }
  return { sanDns: dedupe(sanDns), sanIp: [] };
}

/**
 * Generate a 2048-bit RSA self-signed certificate using the system `openssl`
 * binary. Returns the PEM-encoded cert and key bodies.
 */
async function generateWithOpenssl(
  input: SelfSignedInput,
): Promise<SelfSignedOutput> {
  const sanLines: string[] = [];
  let i = 1;
  for (const dns of input.sanDns) {
    sanLines.push(`DNS.${i++} = ${dns}`);
  }
  i = 1;
  for (const ip of input.sanIp) {
    sanLines.push(`IP.${i++} = ${ip}`);
  }
  const configBody = [
    "[req]",
    "distinguished_name = req_dn",
    "x509_extensions = v3_req",
    "prompt = no",
    "",
    "[req_dn]",
    `CN = ${input.commonName || "wos"}`,
    "",
    "[v3_req]",
    "keyUsage = critical, digitalSignature, keyEncipherment",
    "extendedKeyUsage = serverAuth",
    "basicConstraints = critical, CA:FALSE",
    ...(sanLines.length > 0
      ? ["subjectAltName = @alt_names", "", "[alt_names]", ...sanLines]
      : []),
    "",
  ].join("\n");

  const id = randomBytes(8).toString("hex");
  const dir = tmpdir();
  const configPath = resolve(dir, `wos-ssl-${id}.cnf`);
  const certPath = resolve(dir, `wos-ssl-${id}.crt`);
  const keyPath = resolve(dir, `wos-ssl-${id}.key`);
  try {
    await writeFile(configPath, configBody, "utf8");
    await runOpenssl([
      "req",
      "-x509",
      "-nodes",
      "-newkey",
      "rsa:2048",
      "-days",
      "3650",
      "-config",
      configPath,
      "-keyout",
      keyPath,
      "-out",
      certPath,
    ]);
    const cert = await readFile(certPath, "utf8");
    const key = await readFile(keyPath, "utf8");
    return { cert, key };
  } finally {
    await Promise.allSettled([
      removeIfExists(configPath),
      removeIfExists(certPath),
      removeIfExists(keyPath),
    ]);
  }
}

async function removeIfExists(path: string): Promise<void> {
  try {
    const { rm } = await import("node:fs/promises");
    await rm(path, { force: true });
  } catch {
    // best-effort cleanup
  }
}

function runOpenssl(args: string[]): Promise<void> {
  return new Promise((resolveProm, rejectProm) => {
    let stderr = "";
    let started = true;
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn("openssl", args, { stdio: ["ignore", "pipe", "pipe"] });
    } catch (e) {
      rejectProm(new Error(`failed to spawn openssl: ${(e as Error).message}`));
      return;
    }
    if (!child.stderr || !child.stdout) {
      started = false;
      rejectProm(new Error("openssl: failed to attach stderr/stdout"));
      return;
    }
    child.stderr.on("data", (chunk: Buffer) => {
      stderr += chunk.toString("utf8");
    });
    child.on("error", (err: Error) => {
      started = false;
      rejectProm(new Error(`openssl not available: ${err.message}`));
    });
    child.on("close", (code: number | null) => {
      if (!started) return;
      if (code === 0) {
        resolveProm();
      } else {
        rejectProm(
          new Error(
            `openssl exited with code ${code ?? "unknown"}${stderr ? `: ${stderr.trim()}` : ""}`,
          ),
        );
      }
    });
  });
}
